/**
 * Icon name mappings for Font Awesome and PatternFly icons
 * This file provides type-safe icon names and their corresponding classes
 */

export type FontAwesomeIconName =
  | 'angle-double-left'
  | 'angle-double-right'
  | 'angle-down'
  | 'angle-left'
  | 'angle-right'
  | 'angle-up'
  | 'arrow-circle-down'
  | 'arrow-circle-up'
  | 'arrow-right'
  | 'arrows-alt-v'
  | 'balance-scale'
  | 'ban'
  | 'bars'
  | 'bell'
  | 'bug'
  | 'caret-down'
  | 'check'
  | 'check-circle'
  | 'clipboard-check'
  | 'code'
  | 'code-branch'
  | 'cog'
  | 'columns'
  | 'compress'
  | 'compress-arrows-alt'
  | 'copy'
  | 'cube'
  | 'cubes'
  | 'database'
  | 'desktop'
  | 'download'
  | 'ellipsis-v'
  | 'exclamation-circle'
  | 'exclamation-triangle'
  | 'expand'
  | 'expand-arrows-alt'
  | 'external-link-alt'
  | 'eye'
  | 'eye-slash'
  | 'file'
  | 'filter'
  | 'flag'
  | 'folder'
  | 'folder-open'
  | 'grip-horizontal'
  | 'grip-vertical'
  | 'history'
  | 'home'
  | 'image'
  | 'info-circle'
  | 'key'
  | 'list'
  | 'lock'
  | 'lock-open'
  | 'long-arrow-alt-down'
  | 'long-arrow-alt-up'
  | 'map-marker'
  | 'memory'
  | 'microchip'
  | 'minus'
  | 'minus-circle'
  | 'pause'
  | 'pause-circle'
  | 'pencil-alt'
  | 'play'
  | 'plus'
  | 'plus-circle'
  | 'power-off'
  | 'print'
  | 'question-circle'
  | 'redo'
  | 'route'
  | 'search'
  | 'search-minus'
  | 'search-plus'
  | 'share-square'
  | 'sort-amount-down'
  | 'sort-amount-down-alt'
  | 'sync-alt'
  | 'table'
  | 'tachometer-alt'
  | 'tag'
  | 'th'
  | 'th-large'
  | 'thumbtack'
  | 'times'
  | 'times-circle'
  | 'trash'
  | 'undo'
  | 'upload'
  | 'user'
  | 'users'
  | 'wrench';

export type FontAwesomeRegularIconName =
  | 'calendar-alt'
  | 'clock'
  | 'comments'
  | 'hdd'
  | 'question-circle'
  | 'window-restore';

export type PatternFlyIconName =
  | 'add-circle-o'
  | 'ansible-tower'
  | 'asleep'
  | 'attention-bell'
  | 'automation'
  | 'blueprint'
  | 'build'
  | 'builder-image'
  | 'bundle'
  | 'catalog'
  | 'cloud-security'
  | 'cloud-tenant'
  | 'cluster'
  | 'connected'
  | 'critical-risk'
  | 'data-processor'
  | 'data-sink'
  | 'data-source'
  | 'degraded'
  | 'disconnected'
  | 'domain'
  | 'enhancement'
  | 'enterprise'
  | 'export'
  | 'flavor'
  | 'import'
  | 'in-progress'
  | 'infrastructure'
  | 'integration'
  | 'middleware'
  | 'migration'
  | 'module'
  | 'monitoring'
  | 'multicluster'
  | 'network'
  | 'off'
  | 'open-drawer-right'
  | 'openshift'
  | 'openstack'
  | 'optimize'
  | 'package'
  | 'pending'
  | 'pficon-network-range'
  | 'pficon-satellite'
  | 'pficon-template'
  | 'pficon-vcenter'
  | 'port'
  | 'private'
  | 'process-automation'
  | 'regions'
  | 'registry'
  | 'replicator'
  | 'repository'
  | 'resource-pool'
  | 'resources-almost-empty'
  | 'resources-almost-full'
  | 'resources-empty'
  | 'resources-full'
  | 'running'
  | 'save'
  | 'security'
  | 'server-group'
  | 'service'
  | 'service-catalog'
  | 'services'
  | 'severity-critical'
  | 'severity-important'
  | 'severity-minor'
  | 'severity-moderate'
  | 'severity-none'
  | 'severity-undefined'
  | 'storage-domain'
  | 'task'
  | 'tenant'
  | 'topology'
  | 'trend-down'
  | 'trend-up'
  | 'unknown'
  | 'virtual-machine'
  | 'volume'
  | 'zone';

/**
 * Get Font Awesome solid icon class
 */
export function getFasIconClass(name: FontAwesomeIconName): string {
  return `fas fa-${name}`;
}

/**
 * Get Font Awesome regular icon class
 */
export function getFarIconClass(name: FontAwesomeRegularIconName): string {
  return `far fa-${name}`;
}

/**
 * Get PatternFly icon class
 */
export function getPficonClass(name: PatternFlyIconName): string {
  return `pf-icon pficon-${name}`;
}


